### ISSUE TITLE
Complete all the .md files 

### ISSUE THREAD

**Issue by viennametta** [CIVICS/ECSA#8]
Especially BLTMatrix.md, LegalArchitecture.md

**Comment by dazzaji** [comment]
Done!  See files at: 

* BLTMatrix.md: https://github.com/CIVICS/ECSA/blob/master/BLTMatrix.md

* GitHubProductionWorkshop.md: https://github.com/CIVICS/ECSA/blob/master/GitHubProductionWorkshop.md

* LegalArchitecture.md: https://github.com/CIVICS/ECSA/blob/master/LegalArchitecture.md

* OpenSourceContractsProjectFeedback.md: https://github.com/CIVICS/ECSA/blob/master/OpenSourceContractsProjectFeedback.md
